name: Build
on: [push, pull_request]
env:
  buildDir: ${{ github.workspace }}/build/

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'
      - name: Build
        run: |
          gem install --verbose xcpretty
          mkdir ${PWD}/__build__
          set -o pipefail && xcodebuild -configuration Release -target "MumbleKit (iOS)" CONFIGURATION_BUILD_DIR="${PWD}/__build__" | xcpretty
